config/routes.rb
Rails.application.routes.draw do
  resource :homepage, only: [:show]
  resource :rsvp, only: [:show]
  resource :registry, only: [:show]
  root "homepages#show"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 before_filter :cors_set_access_control_headers

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
  end
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  def show

  end
end

app/controllers/registries_controller.rb
class RegistriesController < ApplicationController

  def show

  end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepages/_boston_tabs.html.erb
  <ul class="tabs boston-tabs">
    <li class="tab-link boston-tab-link" data-tab="tab-1">Saturday</li>
    <li class="tab-link boston-tab-link" data-tab="tab-2">Sunday</li>
    <li class="tab-link boston-tab-link" data-tab="tab-3">Monday</li>
  </ul>

  <div id="tab-1" class="tab-content">
    <span data-tab="tab-1" class="x-circle">x</span>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
  <div id="tab-2" class="tab-content">
    <span data-tab="tab-2" class="x-circle">x</span>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
  <div id="tab-3" class="tab-content">
    <span data-tab="tab-3" class="x-circle">x</span>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>

app/views/homepages/_flexbox.html.erb
<div class="flex-boxes">
  <a href="javascript:void(0)" class="flex-box">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1_dark.png" alt="">
    <h1 class="flex-title">Flex Box Item</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum molestiae fugiat tenetur fugit atque dignissimos, fugiat natus vitae.</p>
  </a>
  <a href="javascript:void(0)" class="flex-box">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_3_dark.png" alt="">
    <h1 class="flex-title">A Flex Box Item</h1>
    <p>Lorem adipisicing elit. Voluptas consectetur tempora quis nam, officia tenetur blanditiis in illo dolor?</p>
  </a>
  <a href="javascript:void(0)" class="flex-box">
    <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_2_dark.png" alt="">
    <h1 class="flex-title">Flex Box Item</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo obcaecati in provident illo.</p>
  </a>
</div>

app/views/homepages/_footer.html.erb
<div id="footer">
  <p><|||||3</p>
</div>

app/views/homepages/_hotels.html.erb
<div id="hotels-section" class="hotels-container container">
  <h2>Accomodations</h2>
  <p class="mention">Mention the Dorobek/Kiernan wedding when booking. Transportation will be provided at each hotel to and from the wedding.</p>
  <div class="row hotel-rows">
    <div class="col-md-4">
      <%= render "liberty" %>
    </div>
    <div class="col-md-4">
      <%= render "westin" %>
    </div>
    <div class="col-md-4">
      <%= render "sheraton" %>
    </div>
  </div>
</div>

app/views/homepages/_liberty.html.erb
<div id="liberty" class="hotel hoverable">
  <div class="content liberty-content">
    <h4>The Liberty Hotel</h4>
    <p>215 Charles St, Boston, MA 02114<br />
    (617) 224-4000<br />
    <a target="_blank" href="http://www.libertyhotel.com">libertyhotel.com</a><br>
    <a target="_blank" href="https://www.starwoodmeeting.com/events/start.action?id=1503185253&key=11E2749A">Book with our group rate</a></p>
    <p>$349/night with wedding rate (call ahead).<p>
    <ul>
      <li>Dog friendly, parking available. Closest T stop is "Charles MGH".</li>
      <li>We had our first date at Liberty's Alibi bar.</li>
      <li>The hotel has three restaurants and will have newly renovated rooms come 2016.</li>
      <li>You're steps from Boston's historic Beacon Hill and an easy walk to the Public Garden,
      Newbury St, and the Freedom Trail.</li>
    </ul>
  </div>
</div>

app/views/homepages/_liberty_tabs.html.erb
<ul class="tabs liberty-tabs">
  <li class="tab-link" data-tab="tab-11">Travel</li>
  <li class="tab-link" data-tab="tab-12">Hotels</li>
  <li class="tab-link" data-tab="tab-13">Things to do in Boston</li>
</ul>

  <div id="tab-11" class="tab-content">
    <span data-tab="tab-11" class="x-circle">x</span>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
  <div id="tab-12" class="tab-content">
    <span data-tab="tab-12" class="x-circle">x</span>
    <h4>The Liberty, phone number, website</h4>
    <p>$349/night, dog friendly, parking, MGH nearest T</p>
    <ul>
      <li>The bride & groom had their first date at Liberty's Alibi bar.</li>
      <li>The hotel has three restaurants and will have newly renovated rooms come 2016.</li>
      <li>You're just steps from boston's historic Beacon Hill with an easy walk to the public garden,
      Newburyport street, and the start of the freedom trail.</li>
    </ul>

    <h4>The Westin Copley, phone number, website</h4>
    <p>$289/night, parking, back bay or Copley nearest T</p>
    <ul>
      <li>Located inside Boston's Prudential Center "The Pru" on the Copley Plaza side.</li>
      <li>You're steps away from the public library & Newbury Street.</li>
      <li>Best yet, Boston's first eataly is coming to the pru and will be open before the wedding weekend.</li>
    </ul>

    <h4>The Sheraton, phone number, website</h4>
    <p>$220/night, parking, prudential nearest T</p>
    <ul>
      <li>Located on the other end of the Pru, you can walk through the Pru from the Westin to the Sheraton.</li>
      <li>You're steps away from Boylston Street near Northeastern and Berklee</li>
    </ul>
  </div>
  <div id="tab-13" class="tab-content">
    <span data-tab="tab-13" class="x-circle">x</span>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>

app/views/homepages/_mobile_nav_bar.html.erb
<div id="mobile-nav-bar">
  <ul>
    <li><%= link_to "Hotels", "#hotels-section" %></li>
    <li><%= link_to "Travel", "#travel-section" %></li>
    <li><%= link_to "Weekend Events", "#weekend-events-section" %></li>
    <li><%= link_to "RSVP", rsvp_path %></li>
    <li><%= link_to "Registry", registry_path %></li>
</div>

app/views/homepages/_nav_bar.html.erb
<div id="desktop-nav-bar">
  <ul>
    <li><%= link_to "RSVP", rsvp_path %></li>
    <li><%= link_to "Weekend Events", "#weekend-events-section" %></li>
    <li><%= link_to "Best of Boston", "#best-of-boston-section" %></li>
    <li><%= link_to "Accommodations", "#hotels-section" %></li>
    <li><%= link_to "Travel", "#travel-section" %></li>
    <li><%= link_to "Registry", registry_path %></li>
  </ul>
</div>
<div class="hash">
  <a target="blank" href="https://www.instagram.com/explore/tags/letsgoghgetmarried/"><span class="hashtag">#<span class="f-letter">L</span>ETS<span class="f-letter">G</span>OGH<span class="f-letter">G</span>ET<span class="f-letter">M</span>ARRIED</span></a>
</div>

app/views/homepages/_plane.html.erb
<div id="plane" class="hoverable travel">
  <div class="content plane-content">
    <p>Fly into Boston Logan international airport (BOS). From Logan you can grab a cab to any of the hotels for roughly $30 or take public transportation known as "the T."</p>
    <p>Find Flights: <%= link_to "hipmunk.com", "http://www.hipmunk.com", target:"_blank" %></p>
  </div>
</div>

app/views/homepages/_sheraton.html.erb
<div id="sheraton" class="hotel hoverable">
  <div class="content sheraton-content">
    <h4>The Sheraton</h4>
    <p>39 Dalton St, Boston, MA 02199<br />
    (617) 236-2000<br />
    <a target="_blank" href="http://www.sheratonbostonhotel.com">sheratonbostonhotel.com</a><br>
    <a target="_blank" href="https://www.starwoodmeeting.com/events/start.action?id=1507316892&key=2CE9A17">Book with our group rate</a></p>
    <p>$229/night with wedding rate (call ahead).
    <ul>
      <li>Parking available. Closest T Stop is "Prudential".</li>
      <li>Located on the other end of the Pru, you can walk through the Pru from the Westin to the Sheraton.</li>
      <li>You're steps away from Boylston Street, Northeastern University and Berklee College of Music. </li>
    </ul>
  </div>
</div>

app/views/homepages/_train.html.erb
<div id="train" class="hoverable travel">
  <div class="content train-content">
    <p>South Station and Back Bay Station are the two main train stations in Boston. All hotels are a quick cab ride or accessible by T.</p>
    <p>Find Trains: <%= link_to "amtrak.com", "http://www.amtrak.com", target:"_blank" %></p>
  </div>
</div>

app/views/homepages/_welcome_note.html.erb
<div id="welcome-section">
  <p>Having friends and family from near and far join together to celebrate is such an incredible thing. We think cake, dance floor air guitars and cake are pretty incredible too. Mmm... cake. We can’t wait to see you in May!</p>
  <p>Love,<br><span id="names">Christina & Matt</span></p>
  <hr />
</div>

app/views/homepages/_westin.html.erb
<div id="westin" class="hotel hoverable">
  <div class="content westin-content">
    <h4>The Westin Copley</h4>
    <p>10 Huntington Ave, Boston, MA 02116<br />
    (617) 262-9600<br />
    <a target="_blank" href="http://www.westincopleyplaceboston.com/">westincopleyplaceboston.com</a><br>
    <a target="_blank" href="https://www.starwoodmeeting.com/events/start.action?id=1507276064&key=34CEA970">Book with our group rate</a></p>
    <p>$289/night with wedding rate (call ahead).</p>
    <ul>
      <li>Parking available, closest T stop is "Back Bay" or "Copley".</li>
      <li>Located inside Boston's Prudential Center "The Pru" on the Copley Plaza side.</li>
      <li>You're steps away from the Public Library & Newbury Street.</li>
      <li>Boston's first Eataly is coming to The Pru and will be open before the wedding weekend.</li>
    </ul>
  </div>
</div>

app/views/homepages/show.html.erb
<%= render "header" %>
<%= render "nav_bar" %>
<%= render "beach_hero" %>
<%# <%= render "mobile_nav_bar" %>
<%= render "welcome_note" %>
<%= render "weekend_events" %>
<hr class="seperator" />
<%= render "best_of_boston" %>
<hr class="seperator" />
<%= render "hotels" %>
<hr class="seperator" />
<%= render "travel" %>
<hr class="seperator" />
<%= render "footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Christina+Matt</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="initial-scale=1" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
  <link href='https://fonts.googleapis.com/css?family=Pinyon+Script' rel='stylesheet' type='text/css'>
  <link rel="icon" type="image/png" href="https://s3.amazonaws.com/mtk-wedding/cheers.png">
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/registries/show.html.erb
<script id='script_myregistry_giftlist_iframe' type='text/javascript' src='http://www.myregistry.com/Visitors/GiftList/iFrames/EmbedRegistry.ashx?r=zI1B3TNeL4QHqtQuk2azrg2'></script>

app/views/reistries/show.html.erb
<script id='script_myregistry_giftlist_iframe' type='text/javascript' src='http://www.myregistry.com/Visitors/GiftList/iFrames/EmbedRegistry.ashx?r=zI1B3TNeL4QHqtQuk2azrg2'></script>

app/views/rsvps/show.html.erb
<div id="rsvp-section">
  <a href="/"><%= image_tag "/arrow.png", id:"arrow" %></a>
  <div id="rsvp-inner-frame">
    <script type="text/javascript" src="http://form.jotform.us/jsform/51855999949181"></script>
  </div>
</div>